context:
  
  data:
    - row:
      - 31
      - ArchShares
      - $0.08
      - $613,726
      - $25,435,847
    - row:
      - 32
      - HeavyCoin
      - $0.16
      - $765,692
      - $3,613,726
    - row:
      - 33
      - SwiftToken
      - $0.32
      - $845,323
      - $4,370,568
    - row:
      - 34
      - NetNextCoin
      - $0.35
      - $125,453
      - $88,125,453
