label: Select
context:
  label: Select
  id: default
  options:
    - value: 1
      text: American
    - value: 2
      text: Belgian
    - value: 3
      text: Hong Kong
    - value: 4
      text: Pandan
